@startuml
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor 阿姨 as Worker

rectangle "阿姨端" {
  (登录/退出) as UC_Login

  package "基础资料" {
    (资料-新增/完善) as UC_ProfileCreate
    (资料-查看) as UC_ProfileRead
    (资料-编辑) as UC_ProfileUpdate
  }

  package "档期管理" {
    (档期-新增) as UC_ScheduleCreate
    (档期-查看) as UC_ScheduleRead
    (档期-编辑) as UC_ScheduleUpdate
    (档期-删除) as UC_ScheduleDelete
  }

  package "订单处理" {
    (接单/拒单) as UC_TakeOrReject
    (查看我的订单) as UC_OrderRead
    (开始服务) as UC_Start
    (完成服务) as UC_Finish
  }
}

Worker --> UC_Login

Worker --> UC_ProfileCreate
Worker --> UC_ProfileRead
Worker --> UC_ProfileUpdate

Worker --> UC_ScheduleCreate
Worker --> UC_ScheduleRead
Worker --> UC_ScheduleUpdate
Worker --> UC_ScheduleDelete

Worker --> UC_TakeOrReject
Worker --> UC_OrderRead
Worker --> UC_Start
Worker --> UC_Finish

@enduml

